## 資料整理+泡泡圖練習__新北市各區老年人口比例跟所得中位數之關係

In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [128]:
pop2018= pd.read_excel("2018年12月鄉鎮市區單一年齡人口數.xlsx")
pop2018.head()
pop2018=pop2018.drop("COUNTY_ID",axis=1)
pop2018.head()

  COUNTY TOWN  TOWN_ID  年齡   男   女
0    連江縣  南竿鄉  9007010   0  36  37
1    連江縣  南竿鄉  9007010   1  45  33
2    連江縣  南竿鄉  9007010   2  42  32
3    連江縣  南竿鄉  9007010   3  39  40
4    連江縣  南竿鄉  9007010   4  36  43

### 人口總數

In [129]:
pop2018['人口總數(男加女)']=pop2018.男+pop2018.女
pop2018.head()

  COUNTY TOWN  TOWN_ID  年齡   男   女  人口總數(男加女)
0    連江縣  南竿鄉  9007010   0  36  37         73
1    連江縣  南竿鄉  9007010   1  45  33         78
2    連江縣  南竿鄉  9007010   2  42  32         74
3    連江縣  南竿鄉  9007010   3  39  40         79
4    連江縣  南竿鄉  9007010   4  36  43         79

In [130]:
pop2018['年齡(new)']=pop2018.年齡+0.5
pop2018=pop2018.drop("年齡",axis=1)

pop2018.head()

  COUNTY TOWN  TOWN_ID   男   女  人口總數(男加女)  年齡(new)
0    連江縣  南竿鄉  9007010  36  37         73      0.5
1    連江縣  南竿鄉  9007010  45  33         78      1.5
2    連江縣  南竿鄉  9007010  42  32         74      2.5
3    連江縣  南竿鄉  9007010  39  40         79      3.5
4    連江縣  南竿鄉  9007010  36  43         79      4.5

In [131]:
pop2018_new=pop2018.groupby(['TOWN_ID','COUNTY','TOWN']).sum()
pop2018_new.head()

                         男      女  人口總數(男加女)  年齡(new)
TOWN_ID COUNTY TOWN
9007010 連江縣    南竿鄉    4304   3359       7663   5100.5
9007020 連江縣    北竿鄉    1353   1072       2425   5100.5
9007030 連江縣    莒光鄉     989    629       1618   5100.5
9007040 連江縣    東引鄉     802    548       1350   5100.5
9020010 金門縣    金城鎮   21565  21760      43325   5100.5

### 老年人口總數

In [132]:
oldpop=pop2018[pop2018['年齡(new)']>65]
oldpop.head()

   COUNTY TOWN  TOWN_ID   男   女  人口總數(男加女)  年齡(new)
65    連江縣  南竿鄉  9007010  44  28         72     65.5
66    連江縣  南竿鄉  9007010  39  27         66     66.5
67    連江縣  南竿鄉  9007010  37  17         54     67.5
68    連江縣  南竿鄉  9007010  35  19         54     68.5
69    連江縣  南竿鄉  9007010  27  19         46     69.5

In [133]:
oldpop=oldpop.groupby(['TOWN_ID','COUNTY','TOWN']).sum()
oldpop.head()
oldpop=oldpop.drop(['男','女','年齡(new)'],axis=1)

oldpop=oldpop.rename(columns={'人口總數(男加女)':'老年人口總數(男加女)'})
oldpop.head()

                     老年人口總數(男加女)
TOWN_ID COUNTY TOWN
9007010 連江縣    南竿鄉           804
9007020 連江縣    北竿鄉           329
9007030 連江縣    莒光鄉           221
9007040 連江縣    東引鄉           113
9020010 金門縣    金城鎮          5655

### 合併

In [134]:
pop2018_new_1 = pd.merge(pop2018_new, oldpop,left_on=['TOWN_ID','COUNTY','TOWN'],right_on=['TOWN_ID','COUNTY','TOWN'])

pop2018_new_1.head()

                         男      女  人口總數(男加女)  年齡(new)  老年人口總數(男加女)
TOWN_ID COUNTY TOWN
9007010 連江縣    南竿鄉    4304   3359       7663   5100.5          804
9007020 連江縣    北竿鄉    1353   1072       2425   5100.5          329
9007030 連江縣    莒光鄉     989    629       1618   5100.5          221
9007040 連江縣    東引鄉     802    548       1350   5100.5          113
9020010 金門縣    金城鎮   21565  21760      43325   5100.5         5655

### 所得中位數(找到的最新資訊為105年)

In [135]:
tax= pd.read_excel("105年綜合所得稅所得總額申報統計_鄉鎮市區.xlsx")
tax.head()
tax=tax[['鄉鎮市區代碼','縣市名稱','鄉鎮市區名稱','中位數']]
tax.columns = ['TOWN_ID','COUNTY','TOWN','中位數']
tax.head()

   TOWN_ID COUNTY TOWN  中位數
0  9007010    連江縣  南竿鄉  795
1  9007020    連江縣  北竿鄉  703
2  9007030    連江縣  莒光鄉  752
3  9007040    連江縣  東引鄉  864
4  9020010    金門縣  金城鎮  718

In [138]:
pop2018_new_2 = pd.merge(pop2018_new_1, tax,left_on=['TOWN_ID','COUNTY','TOWN'],right_on=['TOWN_ID','COUNTY','TOWN'])
pop2018_new_2.head()

   TOWN_ID COUNTY TOWN      男      女  人口總數(男加女)  年齡(new)  老年人口總數(男加女)  中位數
0  9007010    連江縣  南竿鄉   4304   3359       7663   5100.5          804  795
1  9007020    連江縣  北竿鄉   1353   1072       2425   5100.5          329  703
2  9007030    連江縣  莒光鄉    989    629       1618   5100.5          221  752
3  9007040    連江縣  東引鄉    802    548       1350   5100.5          113  864
4  9020010    金門縣  金城鎮  21565  21760      43325   5100.5         5655  718

### 老年人口比例
* 老年人口比例=老年人口/人口總數

In [143]:
pop2018_new_2['老年人口比例(%)']=pop2018_new_2['老年人口總數(男加女)']/pop2018_new_2['人口總數(男加女)']*100
pop2018_new_2.head()

,TOWN_ID,COUNTY,TOWN,男,女,人口總數(男加女),年齡(new),老年人口總數(男加女),中位數,老年人口比例,老年人口比例(%)
0,9007010,連江縣,南竿鄉,4304,3359,7663,5100.5,804,795,10.491974,10.491974
1,9007020,連江縣,北竿鄉,1353,1072,2425,5100.5,329,703,13.567010,13.567010
2,9007030,連江縣,莒光鄉,989,629,1618,5100.5,221,752,13.658838,13.658838
3,9007040,連江縣,東引鄉,802,548,1350,5100.5,113,864,8.370370,8.370370
4,9020010,金門縣,金城鎮,21565,21760,43325,5100.5,5655,718,13.052510,13.052510

In [147]:
new_taipei=pop2018_new_2[pop2018_new_2['COUNTY']=='新北市']
new_taipei

,TOWN_ID,COUNTY,TOWN,男,女,人口總數(男加女),年齡(new),老年人口總數(男加女),中位數,老年人口比例,老年人口比例(%)
256,65000010,新北市,板橋區,270394,284348,554742,5100.5,77614,628,13.991008,13.991008
257,65000020,新北市,三重區,189559,196267,385826,5100.5,54065,575,14.012793,14.012793
258,65000030,新北市,中和區,200054,212432,412486,5100.5,63658,633,15.432766,15.432766
259,65000040,新北市,永和區,104839,116259,221098,5100.5,39092,696,17.680847,17.680847
260,65000050,新北市,新莊區,203713,214041,417754,5100.5,45931,596,10.994748,10.994748
261,65000060,新北市,新店區,145142,157089,302231,5100.5,51409,666,17.009837,17.009837
262,65000070,新北市,樹林區,91732,92214,183946,5100.5,20524,585,11.157622,11.157622
263,65000080,新北市,鶯歌區,43281,43080,86361,5100.5,9873,555,11.432244,11.432244
264,65000090,新北市,三峽區,57947,57873,115820,5100.5,13249,595,11.439302,11.439302
265,65000100,新北市,淡水區,83082,90420,173502,5100.5,24483,648,14.111077,14.111077
266,65000110,新北市,汐止區,97696,102839,200535,5100.5,26265,636,13.097464,13.097464
267,65000120,新北市,瑞芳區,20168,19814,39982,5100.5,6995,526,17.495373,17.495373
268,65000130,新北市,土城區,116707,120194,236901,5100.5,25294,577,10.677034,10.677034
269,65000140,新北市,蘆洲區,98883,102449,201332,5100.5,19965,582,9.916456,9.916456
270,65000150,新北市,五股區,43507,42822,86329,5100.5,9371,561,10.854985,10.854985
271,65000160,新北市,泰山區,38925,39783,78708,5100.5,8726,625,11.086548,11.086548
272,65000170,新北市,林口區,53500,56581,110081,5100.5,11549,758,10.491365,10.491365
273,65000180,新北市,深坑區,11841,11793,23634,5100.5,3225,604,13.645595,13.645595
274,65000190,新北市,石碇區,4220,3511,7731,5100.5,1639,518,21.200362,21.200362
275,65000200,新北市,坪林區,3633,2979,6612,5100.5,1633,548,24.697520,24.697520
276,65000210,新北市,三芝區,11839,11139,22978,5100.5,3910,497,17.016276,17.016276
277,65000220,新北市,石門區,6266,5849,12115,5100.5,2009,510,16.582749,16.582749
278,65000230,新北市,八里區,19410,19496,38906,5100.5,4705,563,12.093250,12.093250
279,65000240,新北市,平溪區,2583,2083,4666,5100.5,1349,523,28.911273,28.911273
280,65000250,新北市,雙溪區,4788,4072,8860,5100.5,2285,531,25.790068,25.790068
281,65000260,新北市,貢寮區,6263,6038,12301,5100.5,2666,503,21.673035,21.673035
282,65000270,新北市,金山區,10730,11044,21774,5100.5,3406,495,15.642509,15.642509
283,65000280,新北市,萬里區,11107,10961,22068,5100.5,3955,507,17.921878,17.921878
284,65000290,新北市,烏來區,3159,3279,6438,5100.5,860,616,13.358186,13.358186

In [159]:
from bubbly.bubbly import bubbleplot 
from plotly.offline import plot

my_bubbleplot= bubbleplot(dataset=new_taipei, x_column='中位數', y_column='老年人口比例(%)', 
    bubble_column='TOWN',size_column='老年人口總數(男加女)', color_column='TOWN', 
    x_title="所得中位數", y_title="老年人口比例(%)", title='2018年新北市各區老年人口比例跟所得中位數之關係',scale_bubble=3, height=700)
 
plot(my_bubbleplot,config={'scrollzoom': True})

'temp-plot.html'